spring.application.name=${SPRING_APP_NAME}
server.port=${SPRING_APP_PORT}

# ===============================
# Routes
# ===============================

spring.cloud.gateway.server.webflux.routes[0].id=${ROUTE_0_ID}
spring.cloud.gateway.server.webflux.routes[0].uri=${ROUTE_0_URI}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=${ROUTE_0_PATH}
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[0].filters[1]=RequestRateLimiter

spring.cloud.gateway.server.webflux.routes[1].id=${ROUTE_1_ID}
spring.cloud.gateway.server.webflux.routes[1].uri=${ROUTE_1_URI}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=${ROUTE_1_PATH}
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[1].filters[1]=RequestRateLimiter


# ===============================
# Redis
# ===============================

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}


# ===============================
# Logging
# ===============================

logging.level.org.springframework.security=${LOG_LEVEL_SECURITY}
logging.level.org.springframework.cloud.gateway=${LOG_LEVEL_GATEWAY}
logging.level.reactor.netty.http.client=${LOG_LEVEL_NETTY}
logging.level.com.pixxy.gateway=${LOG_LEVEL_APP}

logging.file.path=${LOG_PATH}
logging.logback.rollingpolicy.max-file-size=${LOG_MAX_FILE_SIZE}
logging.logback.rollingpolicy.max-history=${LOG_MAX_HISTORY}


# ===============================
# Actuator + Tracing
# ===============================

management.endpoints.web.exposure.include=${ACTUATOR_EXPOSE}
management.tracing.enabled=${TRACING_ENABLED}
management.tracing.sampling.probability=${TRACING_PROBABILITY}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}