apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixxy-notiservice
  namespace: pixxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixxy-notiservice
  template:
    metadata:
      labels:
        app: pixxy-notiservice
    spec:
      containers:
        - name: pixxy-notiservice
          image: ravikumar4224/pixxy-notiservice:IMAGE_TAG
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: pixxy-notiservice-configmap
            - secretRef:
                name: pixxy-notiservice-secret
