apiVersion: v1
kind: Service
metadata:
  name: pixxy-notiservice-service
  namespace: pixxy
  labels:
    app: pixxy-notiservice-service
spec:
  type: ClusterIP
  selector:
    app: pixxy-notiservice-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
